# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_addLp_int <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_addLp_int`, x, y, nthread)
}

Rcpp_addLp_num <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_addLp_num`, x, y, nthread)
}

Rcpp_diffLp_int <- function(x, lag, differences, nthread) {
    .Call(`_LauraeCpp_Rcpp_diffLp_int`, x, lag, differences, nthread)
}

Rcpp_diffLp_num <- function(x, lag, differences, nthread) {
    .Call(`_LauraeCpp_Rcpp_diffLp_num`, x, lag, differences, nthread)
}

Rcpp_diffLp_simd_int <- function(x, lag, differences, nthread) {
    .Call(`_LauraeCpp_Rcpp_diffLp_simd_int`, x, lag, differences, nthread)
}

Rcpp_diffLp_simd_num <- function(x, lag, differences, nthread) {
    .Call(`_LauraeCpp_Rcpp_diffLp_simd_num`, x, lag, differences, nthread)
}

Rcpp_divLp_num <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_divLp_num`, x, y, nthread)
}

Rcpp_meanLp_int <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_meanLp_int`, x, nthread)
}

Rcpp_meanLp_num <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_meanLp_num`, x, nthread)
}

Rcpp_mulLp_int <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_mulLp_int`, x, y, nthread)
}

Rcpp_mulLp_num <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_mulLp_num`, x, y, nthread)
}

Rcpp_subLp_int <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_subLp_int`, x, y, nthread)
}

Rcpp_subLp_num <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_subLp_num`, x, y, nthread)
}

Rcpp_sumLp_int <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_sumLp_int`, x, nthread)
}

Rcpp_sumLp_num <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_sumLp_num`, x, nthread)
}

