# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_addLp_int <- function(x, y, nthread) {
    .Call(`_LauraeCpp_Rcpp_addLp_int`, x, y, nthread)
}

Rcpp_meanLp_num <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_meanLp_num`, x, nthread)
}

Rcpp_sumLp_num <- function(x, nthread) {
    .Call(`_LauraeCpp_Rcpp_sumLp_num`, x, nthread)
}

